FROM node:14.16.0-alpine

# node_modulesインストール
WORKDIR /usr/src/app
COPY app/package.json ./
COPY app/yarn.lock ./
RUN yarn install

# ソースコピー
COPY app/.env ./
COPY app/tsconfig.json ./
COPY app/src ./src

# ビルド
CMD ["yarn", "build"]