version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    command: yarn start

  mysql:
    image: mysql:8.0.23
    volumes:
      - ./mysql_data_bk:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password